### ISSUE TITLE
Add spring security implementation

### ISSUE THREAD

**Issue by aLeXcBa1990** [adminfaces/admin-starter-springboot#5]
If you let me, I could help with this, but I need some help

**Comment by rmpestano** [comment]
Yes, please I've created adminfaces/admin-starter-springboot-security so you can send a PR there.

Thanks in advance.

**Comment by aLeXcBa1990** [comment]
Hi, I have integrated spring security into the project, can you help me to do the PR?

**Comment by rmpestano** [comment]
Hi @aLeXcBa1990, 

Have you used [admin-starter-springboot](https://github.com/adminfaces/admin-starter-springboot) as base of your project? 

To make the PR please follow this steps (I'm assuming you never created a PR before):

1. Fork admin-starter-springboot-security project: https://github.com/adminfaces/admin-starter-springboot-security (top right fork button)
2. Clone the recently forked project, it's url will be somethinh like `https://github.com/aLeXcBa1990/admin-starter-springboot-security`
3. Copy the contents of the project you've added Spring Security support into the recently cloned project
4. Commit & push your changes
5. Go to your repo: https://github.com/aLeXcBa1990/admin-starter-springboot-security/pulls and create a new pull request.

**Comment by aLeXcBa1990** [comment]
Yes, I used it.
Really is my first PR, but I could not Fork the admin-starter-springboot-security project.
Thank for the guide, I try now to make the PR.

**Comment by rmpestano** [comment]
No problem, I can copy your project if you have problems with the PR, is this one right? https://github.com/aLeXcBa1990/admin-starter-springboot/commits/master

**Comment by aLeXcBa1990** [comment]
I have already made the PR. Im waiting for any comment or suggestion

**Comment by rmpestano** [comment]
Wonderful! I'll make some tests and accept it ASAP. Thank you very much!
